title: Zayan Niaz's Portfolio
domain: slyz1228.github.io
url: https://slyz1228.github.io # site url
baseurl: /website/ # apply repo name if use it under gh-pages branch

repo: https://github.com/SlyZ1228/website
comments: false

# Build settings
markdown    : kramdown
highlighter : rouge

source: ./subpages
destination: ./_site

# Author settings
author: Zayan Niaz

# social settings
og_locale: "en_US"

kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids:       true
  toc_levels:     1..3